### ISSUE TITLE
Removal of "+New" buttons from gallery view. CSS file upload through tweaks isn't working

### ISSUE THREAD

**Issue by MYShokh** [notion-enhancer/notion-enhancer.github.io#8]
BEFORE MAKING A FEATURE REQUEST, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

FEATURE REQUESTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What makes the feature necessary?**

**How would the feature work?**

**Comment by dragonwocky** [comment]
Try this snippet:
```css
.notion-gallery-view .notion-collection-item + :last-child { display: none !important; }
```
